### ISSUE TITLE
What is that?

### ISSUE THREAD

**Issue by Anduin2017** [lalxyy/unified-server-model#1]

**Comment by lalxyy** [comment]
Previously we talked about "Almost all of the web back-end frameworks and projects has some shared features" in Qzone. That's my idea, a unified server model. Seems like a standard though. However I'm afraid that... it may be a stupid idea.

**Comment by Anduin2017** [comment]
Sounds good, like MVC? If you can define something really can be shared by most projects it would work so popular!
